language: python
python:
  - "2.6"
  - "2.7"
env:
  - OASTATS_SETTINGS=pipeline.settings_test
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install importlib unittest2; fi
  - pip install -r requirements.txt
services:
  - mongodb
script: nosetests tests