version: 1
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: ERROR
    filename: 'pipeline.log'
    formatter: full
loggers:
  pipeline:
    handlers: [console]
  pipeline.requests:
    handlers: [file]
    propagate: false
formatters:
  full:
    format: '%(asctime)s %(err_type)s: %(msg)s'
